# Generated by Django 4.2.7 on 2024-03-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='priority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.priority', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='todo.priority', verbose_name='Приоритет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
